language: python
python:
- '3.6'
script:
- python tests.py
deploy:
  provider: script
  #https://docs.travis-ci.com/user/deployment/script
  script: bash $TRAVIS_BUILD_DIR/travis_deploy.sh
  on: pablo
