language: python
python:
    - "3.6"
script:
    - python tests.py
    
after_success:
    - docker tag tfm-diego-heroku-web:latest registry.heroku.com/tfm-diego/web
    - docker push registry.heroku.com/tfm-diego/web

    - docker tag tfm-diego-worker:latest registry.heroku.com/tfm-diego/worker
    - docker push registry.heroku.com/tfm-diego/worker

    - heroku container:release web worker -a tfm-diego