#imagen con alpine python 3.5, jdk8, django
FROM frolvlad/alpine-python-machinelearning

ENV HOME=/home
ENV PROYECTO=tfm_diego


#dependencias java y glibc
RUN apk --update add openjdk8-jre && \
	apk --no-cache add ca-certificates wget && \
	wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
	wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk && \
	apk add glibc-2.28-r0.apk && \
	apk add git
COPY static/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu/ 
COPY static/sourcemeter-8.2.0-x64-linux $HOME/$PROYECTO/static/sourcemeter-8.2.0-x64-linux/

ENV GCONV_PATH=/usr/lib/x86_64-linux-gnu/gconv
ENV JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre/bin
ENV PATH ${PATH}:$JAVA_HOME

#DEPENDENCIAS SERVICIO WEB
RUN pip  install --upgrade pip
RUN pip3 install Django
RUN pip3 install requests
RUN pip3 install gunicorn
RUN pip3 install GitPython



	

