FROM  paberlo/alpine-scikit-django-jdk8:v1

# variables para dockerizacion
ENV HOME=/home
ENV PROYECTO=tfm_diego

#copiar codigo
COPY webapp/ $HOME/$PROYECTO

# cambiar punto de entrada al directorio del proyecto
WORKDIR $HOME/$PROYECTO
#RUN pip install django-rq

CMD python3 manage.py runserver 0.0.0.0:8000

